<!-- Base theme - Fixed + Grids begins / Début du thème Base - Fixe + Grilles -->
		<div id="cn-head-base">
			<section>
				<h2>En-tête (Thème base - Fixe + Grilles) / <span lang="en">Header (Base theme - Fixed + Grids)</span></h2>
				<ul>
					<li>liste à puces (<code>ul</code>) premier niveau - apparence par défaut / <span lang="en">unordered list (<code>ul</code>) first level default appearance</span>
						<ul>
							<li>liste à puces (<code>ul</code>) deuxième niveau - apparence par défaut / <span lang="en">unordered list (<code>ul</code>) second level default appearance</span></li>
						</ul>
					</li>
				</ul>
			</section>
		</div>
<!-- Base theme - Fixed + Grids ends / Fin du thème Base - Fixe + Grilles -->
