<!-- Base theme - Fixed + Grids begins / Début du thème Base - Fixe + Grilles -->
		<div id="cn-head-base">
			<section>
				<h2>En-tête (Thème base - Fixe + Grilles)</h2>
				<ul>
					<li>liste à puces (<code>ul</code>) premier niveau - apparence par défaut
						<ul>
							<li>liste à puces (<code>ul</code>) deuxième niveau - apparence par défaut</li>
						</ul>
					</li>
				</ul>
			</section>
		</div>
<!-- Base theme - Fixed + Grids ends / Fin du thème Base - Fixe + Grilles -->
