<!-- CSS Grid System begins / Début du système de grille de CSS -->
	<link href="../grids/css/grid.css" media="screen" rel="stylesheet" />
<!-- CSS Grid System ends / Fin du système de grille de CSS -->
<!-- Base theme - Fixed + Grids begins / Début du thème Base - Fixe + Grilles -->
	<link href="../theme-base-fixed-grids/css/framework-default-theme-base.css" media="screen" rel="stylesheet" id="framework-responsive" />
	<link href="../theme-base-fixed-grids/css/theme-base-fixed-grids.css" rel="stylesheet" />
	<!--[if IE 7]><link href="../theme-base-fixed-grids/css/theme-base-fixed-grids-ie7.css" rel="stylesheet" /><![endif]-->
	<!--[if lte IE 6]><link href="../theme-base-fixed-grids/css/theme-base-fixed-grids-ie6.css" rel="stylesheet" /><![endif]-->
<!-- Base theme - Fixed + Grids ends / Fin du thème Base - Fixe + Grilles -->
