<!-- Base theme - Fixed + Grids begins / Début du thème Base - Fixe + Grilles -->
		<div id="cn-foot-base">
			<h3>Footer (Base theme - Fixed + Grids) / <span lang="fr">Pied de page (Thème base - Fixe + Grilles)</span></h3>
			<ul>
				<li>unordered list (<code>ul</code>) first level default appearance / <span lang="fr">liste à puces (<code>ul</code>) premier niveau - apparence par défaut</span>
					<ul>
						<li>unordered list (<code>ul</code>) second level default appearance / <span lang="fr">liste à puces (<code>ul</code>) deuxième niveau - apparence par défaut</span></li>
					</ul>
				</li>
			</ul>
		</div>
<!-- Base theme - Fixed + Grids ends / Fin du thème Base - Fixe + Grilles -->
