<!-- Base theme - Fixed + Grids begins / Début du thème Base - Fixe + Grilles -->
		<div id="cn-head-base">
			<section>
				<h2>Header (Base theme - Fixed + Grids)</h2>
				<ul>
					<li>unordered list (<code>ul</code>) first level default appearance
						<ul>
							<li>unordered list (<code>ul</code>) second level default appearance</li>
						</ul>
					</li>
				</ul>
			</section>
		</div>
<!-- Base theme - Fixed + Grids ends / Fin du thème Base - Fixe + Grilles -->
