<!-- Base theme - Fluid begins / Début du thème Base - Fluide -->
		<div id="cn-foot-base">
			<h3>Pied de page (Thème base - Fluide) / <span lang="en">Footer (Base theme - Fluid)</span></h3>
			<ul>
				<li>liste à puces (<code>ul</code>) premier niveau - apparence par défaut / <span lang="en">unordered list (<code>ul</code>) first level default appearance</span>
					<ul>
						<li>liste à puces (<code>ul</code>) deuxième niveau - apparence par défaut / <span lang="en">unordered list (<code>ul</code>) second level default appearance</span></li>
					</ul>
				</li>
			</ul>
		</div>
<!-- Base theme - Fluid ends / Fin du thème Base - Fluide -->
