<!-- Base theme - Fluid begins / Début du thème Base - Fluide -->
		<div id="cn-head-base">
			<section>
				<h2>Header (Base theme - Fluid) / <span lang="fr">En-tête (Thème base - Fluide)</span></h2>
				<ul>
					<li>unordered list (<code>ul</code>) first level default appearance / <span lang="fr">liste à puces (<code>ul</code>) premier niveau - apparence par défaut</span>
						<ul>
							<li>unordered list (<code>ul</code>) second level default appearance / <span lang="fr">liste à puces (<code>ul</code>) deuxième niveau - apparence par défaut</span></li>
						</ul>
					</li>
				</ul>
			</section>
		</div>
<!-- Base theme - Fluid ends / Fin du thème Base - Fluide -->
