<!-- Base theme - Fluid begins / Début du thème Base - Fluide -->
		<div id="cn-head-base">
			<section>
				<h2>En-tête (Thème base - Fluide)</h2>
				<ul>
					<li>liste à puces (<code>ul</code>) premier niveau - apparence par défaut
						<ul>
							<li>liste à puces (<code>ul</code>) deuxième niveau - apparence par défaut</li>
						</ul>
					</li>
				</ul>
			</section>
		</div>
<!-- Base theme - Fluid ends / Fin du thème Base - Fluide -->
