<!-- Base theme - Fluid begins / Début du thème Base - Fluide -->
	<link href="../theme-base-fluid/css/theme-base-fluid.css" rel="stylesheet" />
	<!--[if IE 7]><link href="../theme-base-fluid/css/theme-base-fluid-ie7.css" rel="stylesheet" /><![endif]-->
	<!--[if lte IE 6]><link href="../theme-base-fluid/css/theme-base-fluid-ie6.css" rel="stylesheet" /><![endif]-->
<!-- Base theme - Fluid ends / Fin du thème Base - Fluide -->
