<!-- Base theme - Fixed begins / Début du thème Base - Fixe -->
		<div id="cn-foot-base">
			<h3>Pied de page (Base - Fixe) / <span lang="en">Footer (Base theme - Fixed)</span></h3>
			<ul>
				<li>liste à puces (<code>ul</code>) premier niveau - apparence par défaut / <span lang="en">unordered list (<code>ul</code>) first level default appearance</span>
					<ul>
						<li>liste à puces (<code>ul</code>) deuxième niveau - apparence par défaut / <span lang="en">unordered list (<code>ul</code>) second level default appearance</span></li>
					</ul>
				</li>
			</ul>
		</div>
<!-- Base theme - Fixed ends / Fin du thème Base - Fixe -->
